#! /usr/bin/env bash

prot="docker"
org="library"
img="alpine"
ver="latest"
tag="bqn"

config_flags="
"

dockerfile="
RUN                                                                            \
    apk update                                                              && \
    apk add make gcc g++ clang musl-dev -t bqn-build-deps                   && \
    apk add bash git binutils libffi-dev -t bqn-runtime-deps                && \
                                                                               \
    git clone https://github.com/dzaima/CBQN.git /tmp/CBQN                  && \
    cd /tmp/CBQN                                                            && \
                                                                               \
    make                                                                       \
        PIE=''                                                                 \
        REPLXX=1                                                            && \
                                                                               \
    apk del --purge bqn-build-deps                                          && \
                                                                               \
    mv /tmp/CBQN/BQN /usr/bin/BQN                                           && \
    rm -rf /tmp/*

CMD = [ '/usr/bin/BQN' ]
"

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- BQN $args
