#! /usr/bin/env bash

prot="docker"
org="lspcontainers"
img="clangd-language-server"
ver="latest"
config_flags="
"

dockerfile=""

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" --force-no-ps1 -- $args
