#! /usr/bin/env bash

prot="docker"
org=""
img="node"
ver="latest"
config_flags="
    -v $img_$ver:/usr/local/
"

if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- npm $args
