#! /usr/bin/env bash

prot="docker"
org="rocker"
img="r-ver"
ver="latest"

# to work on dgkf/debugadapter, need to work around docker macos host network
# sharing issues

config_flags="
    -v rlib_$ver:/usr/local/lib/R/site-library
"

dockerfile="
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libfontconfig1-dev \
        libssl-dev \
        libgit2-dev \
        zlib1g-dev \
        libtool \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        libudunits2-dev \
        proj-bin \
        gdal-bin \
        libgdal-dev
"

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- R $args
