#! /usr/bin/env bash

prot="docker"
org="rocker"
img="tidyverse"
ver="devel"
config_flags="
    -v rlib_${org}_${image}_${ver}:/usr/local/lib/R/site-library
    -v /tmp:/tmp
"

dockerfile="
RUN sudo apt-get update && \
    sudo apt-get install -y \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev
"

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- R $args

