#! /usr/bin/env bash

scriptname="r-ver-pandoc"

prot="docker"
org="rocker"
img="r-ver"  # custom built quarto/pandoc
ver="latest"
config_flags="
    -v rlib_${org}_${img}_${ver}:/usr/local/lib/R/site-library
"

dockerfile="
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        libudunits2-dev \
        proj-bin \
        gdal-bin \
        libgdal-dev \
        libglib2.0-dev

RUN /rocker_scripts/install_pandoc.sh
"

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- R $args
