#! /usr/bin/env bash

prot="docker"
org="rocker"
img="verse"  # use "verse" for quarto add-in
ver="latest"
config_flags="
    -v rlib_${org}_${image}_${ver}:/usr/local/lib/R/site-library
    -v /tmp:/tmp
    --platform=linux/amd64
"

dockerfile="
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libharfbuzz-dev \
        libfribidi-dev \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        libudunits2-dev \
        proj-bin \
        gdal-bin \
        libgdal-dev \
        valgrind
"

# quote args using printf over @Q for older bash versions
if [ $# -eq 0 ]; then args=""; else args=$(printf "%q " "$@"); fi
source "$(dirname $0)/_launch.sh" -- R $args
