#! /usr/bin/env bash

prot="docker"
org=""
img="rust"
ver="latest"
config_flags="
    -v rust_cargo_$ver:/usr/local/cargo
    -v rust_rustup_$ver:/usr/local/rustup
"

dockerfile="
RUN rustup +nightly component add rust-analyzer-preview
RUN echo '#!/usr/bin/env bash'               > /usr/local/bin/rust-analyzer
RUN echo 'rustup run nightly rust-analyzer' >> /usr/local/bin/rust-analyzer
RUN chmod +x /usr/local/bin/rust-analyzer
"

source "$(dirname $0)/_launch.sh"
