#! /usr/bin/env bash

prot="docker"
org=""
img="rust"
ver="latest"
config_flags="
    -v rust_cargo_$ver:/usr/local/cargo
    -v rust_rustup_$ver:/usr/local/rustup
"

dockerfile=$(cat <<EOF
RUN rustup +nightly component add rust-analyzer-preview \
 && echo '#! /usr/bin/env bash\nrustup run nightly rust-analyzer' > /usr/local/bin/rust-analyzer \
 && chmod +x /usr/local/bin/rust-analyzer
EOF
)

source "$(dirname $0)/_launch.sh"
